name: Doc build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v2
      # Setup node with version 12.x and NPM registry url
      - uses: actions/setup-node@v1
        with:
          node-version: "16.14.1"
      # Run npm install to install project packages
      - run: yarn install --frozen-lockfile
      # npm run build to build the project
      - run: yarn build
      # publish the files to NPM
